### PR TITLE
Add separate link types

### PR DESCRIPTION
**Pull request by SolitudeSF**
Not sure about the names

### CODE REVIEW

**Comment by SolitudeSF** [comment]
alternative is including links into `file` and `directory` types by default, which is what `fd` does, and IMO is reasonable enough, and if you want to exclude symlinks, you could just add `-t-=link`.

**Comment by Gruruya** [comment]
Changed my mind and added `lfile` and `ldir` 9300d3f426b49d76c9a4676ff25160ee3f9e1be7

**Comment by SolitudeSF** [comment]
why? i struggle to find a reason where you commonly want to treat file-links differently from regular files. but ok.

**Comment by Gruruya** [comment]
Mainly duplicates, I guess consistency, but `-tf -tlf` or `-t,=,f,lf` is a bit painful.  
Maybe exactly `-tf` is files+links and anything beyond `-tfi` is just files, not sure.

**Pull request closed without merging**
