### PR TITLE
Add hyperlink support

### PR DESCRIPTION
**Pull request by SolitudeSF**
Should i override `hyperlink` option to false if stdout is not terminal? Or should i handle it like color option?

### CODE REVIEW

**Comment by Gruruya** [comment]
We should handle it the same as `--color`.  
I'm thinking of basing whether to enable it or not by default depending on `$TERM`, is there a better way you know of?

**Comment by SolitudeSF** [comment]
So does the color, but im asking about implicit disabling.

**Comment by Gruruya** [comment]
> So does the color, but im asking about implicit disabling.

Right sorry, that's what I meant. I think it's better to keep it enabled regardless of if stdout is a tty or not.

**Comment by SolitudeSF** [comment]
Now hyperlinks are implicitly disabled if stdout isnt tty.

**Comment by Gruruya** [comment]
Alright, seems good.

For the record, the links aren't working on the machine I'm testing this on, is the encoding supposed to return `file://host.domain/path` instead of `file://host/path`?

**Pull request merged**
